name: Build Windows
on:
workflow_dispatch:
push:
tags:
- 'v*.*.*'


jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
with:
lfs: true
- uses: actions/cache@v4
with:
path: |
~/.cache
Library
key: ${{ runner.os }}-unity-${{ hashFiles('**/Packages/manifest.json') }}
- name: Build
uses: game-ci/unity-builder@v4
env:
UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
with:
unityVersion: 2022.3.41f1
targetPlatform: StandaloneWindows64
buildName: RobinsonsCurvival
buildPath: Builds/Windows
- name: Upload artifact
uses: actions/upload-artifact@v4
with:
name: build-windows
path: Builds/Windows
